#!/usr/bin/env python3
"""Write a components.yaml for a no-hardware Phase 5 bringup on Thor, derived
from the production f1tenth_bringup/config/components.yaml at run time (so it
cannot drift from it).

  --empty NAME ...        keep component NAME registered but with no launch
                          files (component_supervisor_node auto-starts every
                          name in _ALWAYS_AUTO_START and indexes the registry
                          by it, so removing the key would crash it at startup)
  --drop-launch FILE ...  remove these launch files from whatever component
                          lists them
  --logger-runs-dir DIR   pass mission_logger_runs_dir:=DIR to
                          mission_logger.launch.py (keeps test runs out of
                          ~/f1tenth_archive)

Prints what was changed relative to production.

Usage: phase5_components.py OUT.yaml [--empty ...] [--drop-launch ...] [--logger-runs-dir DIR]
"""
import argparse
import os

import yaml
from ament_index_python.packages import get_package_share_directory


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('out')
    ap.add_argument('--empty', nargs='*', default=[])
    ap.add_argument('--drop-launch', nargs='*', default=[])
    ap.add_argument('--logger-runs-dir')
    a = ap.parse_args()
    src = os.path.join(get_package_share_directory('f1tenth_bringup'), 'config', 'components.yaml')
    with open(src) as f:
        reg = yaml.safe_load(f)
    comps = reg['components']
    changes = []
    for name in a.empty:
        if name not in comps:
            raise SystemExit(f'unknown component {name}')
        changes.append(f'{name}: emptied (was {[e["launch_file"] for e in comps[name]]})')
        comps[name] = []
    for name, entries in comps.items():
        kept = [e for e in entries if e['launch_file'] not in a.drop_launch]
        for e in entries:
            if e not in kept:
                changes.append(f'{name}: dropped {e["launch_file"]}')
        comps[name] = kept
    if a.logger_runs_dir:
        for e in comps['diagnostics']:
            if e['launch_file'] == 'mission_logger.launch.py':
                e.setdefault('args', {})['mission_logger_runs_dir'] = a.logger_runs_dir
                changes.append(f'diagnostics: mission_logger_runs_dir:={a.logger_runs_dir}')
    with open(a.out, 'w') as f:
        f.write(f'# Generated by scripts/jazzy_parity/phase5_components.py from {src}\n')
        for c in changes:
            f.write(f'#   {c}\n')
        yaml.safe_dump(reg, f, sort_keys=False)
    print('\n'.join(changes))


if __name__ == '__main__':
    main()
