"""safe_corridor.py -- iterative convex decomposition (IRIS / safe-flight-
corridor family) of the free space around the MPC's own reference centreline,
as a replacement for costmap_boundary.py's three nearest-occupied-cell
half-planes.

Pure functions, no rclpy dependency, independently unit-testable -- the same
"pure logic separate from ROS glue" split costmap_boundary.py,
costmap_renderer.py and semantic_layer.py already use in this package.

BUILD-ONLY AS OF THIS COMMIT. Nothing imports this module yet. See
costmap_boundary_node.py's own `use_convex_polytope` parameter (default
False) for the wiring, and mpc_solver.py's `boundary_max_sources` /
`boundary_slack` for the consumer side. `use_hard_boundary_constraints` in
MPC_corr.py stays False, so none of this reaches a solve on the default
configuration.


WHAT IS WRONG WITH THE NEAREST-CELL HALF-PLANES
-----------------------------------------------
costmap_boundary.extract_boundary_constraints picks the single nearest
occupied cell in each of three angular sectors and emits a half-plane
tangent at that cell whose normal points along robot->cell. Three separate
problems, all structural rather than tuning:

  1. THE PLANE IS INFINITE. One occupied cell 2 m off to the side produces a
     half-plane that also cuts off space 5 m directly ahead, where nothing
     was ever observed. The constraint is generated by one cell but applies
     everywhere.

  2. THE NORMAL IS robot->cell, NOT THE WALL'S OWN NORMAL. A wall observed
     obliquely yields a plane that slices diagonally across free floor,
     because the direction from the robot to the nearest cell of a wall is
     not the direction the wall actually faces unless the robot happens to
     be square-on to it.

  3. THREE CONSTRAINTS DISCARD THE REST OF THE MAP. Everything not nearest
     in one of the three sectors is simply not represented.

And it was computed from the robot pose alone, independently of the
corridor the MPC is actually tracking, so the reference could sit outside
the feasible set with nothing in the stack detecting that it had.


THE METHOD
----------
The nearest-cell extraction is, in effect, the FIRST ITERATION of the IRIS
inflation below. The fix is to not stop after one:

    seed   = points on the REFERENCE CENTRELINE (not the robot pose)
    points = blocked cells within r_local of the seed set
    while points and len(faces) < max_faces:
        p = closest remaining blocked point to the seed set
        s = the seed point p is closest to
        n = (p - s) / |p - s|                  # face normal
        b = n . p                              # plane TANGENT AT p
        faces.append((n, b))
        points = [q for q in points if n . q < b]   # drop the far side
    -> polytope {x : A x <= b}

Every face therefore has a real observed obstacle cell TOUCHING it, which is
exactly what problems 1 and 3 above are missing: a face is only ever placed
where something was actually seen, and the loop keeps going until either the
blocked set is exhausted (the polytope is then the full free region, not a
three-sector sample) or max_faces is hit.

Problem 2 is fixed by construction too, though it is worth being precise
about how: the normal is still a point-to-point direction, but it is seed->
obstacle where the seed is the nearest point of the REFERENCE, not the robot
pose. For a corridor running alongside a wall that is the wall's own normal,
because the closest point of the centreline to a wall cell is perpendicularly
opposite it. The diagonal slice came from measuring the direction from a
single robot pose; measuring it from the nearest reference point instead
removes it.

max_faces is capped (see MAX_FACES_DEFAULT) because each face is a QP row at
every horizon stage. When the cap is hit with blocked points still
un-separated, that is REPORTED (`cap_hit`), not silently accepted.


SEEDING ON THE REFERENCE -- THE POINT OF THE CHANGE
---------------------------------------------------
The polytope is inflated around the corridor centreline, not the car pose.
The centreline is then inside the polytope BY CONSTRUCTION, so the MPC's own
reference can never be infeasible with respect to the constraints the MPC is
handed. That structurally removes the constraints-versus-reference conflict
the nearest-cell design could produce (and did): with a robot-seeded
polytope, nothing anywhere in the stack was checking that the corridor the
terminal cost pulls toward is inside the halfspaces the solver must respect.

"By construction" is a claim that has to survive a curved corridor, and a
single convex body cannot contain an arbitrarily curved centreline while
still excluding the obstacles on the inside of the bend. inflate_polytope
therefore does not pretend otherwise: it keeps a seed point only while that
point stays inside the polytope, and reports `covered_fraction` -- the
leading fraction of the supplied centreline the returned polytope actually
contains. The containment INVARIANT (every covered seed satisfies A x <= b)
holds unconditionally and is asserted; the COVERAGE is what degrades on a
tight bend, visibly, as a number the caller can refuse to act on.

FOLLOW-UP, deliberately not this commit: per-segment polytopes with stage
assignment -- one polytope per group of horizon stages, each seeded on that
group's own arc of the centreline, so a bend is covered by a chain of convex
bodies instead of one. That is the full safe-flight-corridor formulation and
it needs a message change (constraints have to carry a stage range), which
is why it is not here. The single-polytope-for-all-stages form below needs
no message change at all: BoundaryConstraintArray is already a variable-
length list of exactly this (normal, offset) shape -- a polytope is just
more rows than three.


BLOCKED CELLS -- ALL THREE CASES ARE NAMED
------------------------------------------
OccupancyGrid.data is int8: 0-100 occupancy, -1 for UNKNOWN. This module
handles three cases by name and never lets one fall through to a default:

  occupied (value >= occupied_threshold) -> BLOCKED, generates faces.
  unknown (value < 0, i.e. -1)           -> BLOCKED. You cannot guarantee
                                            free space you have not
                                            observed, and this is feeding a
                                            hard (or heavily penalised)
                                            constraint.
  outside the grid                       -> BLOCKED, via an EXPLICIT
                                            in-bounds mask, never an
                                            unchecked index and never a
                                            silent default.

This INVERTS costmap_boundary.py's own convention, which is deliberate and
is the reason this module exists as a separate file rather than an extra
function in that one. There, unknown and out-of-bounds both collapse to "no
data" and produce NO constraint -- which is the permissive answer, correct
for the advisory front_clearance scalar that module also feeds, and wrong
for a hard constraint. See classify_local_cells' own docstring for the
measurement showing what today's permissive out-of-bounds handling actually
does.

classify_local_cells reports `unknown_fraction` so a caller can tell a
polytope carved out of genuinely observed free space from one whose walls
are made of unexplored cells. If unknown cells (or anything else) squeeze
the result below a usable size, polytope_report flags it DEGENERATE and the
caller is expected to refuse it -- this module never silently shrinks and
hands back something unusable-but-plausible.
"""

import math
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

# Faces cap. Each face becomes one QP row at EVERY horizon stage (see
# mpc_solver.py's own _solve_rti), so at N=20 a cap of 8 is already 160
# rows -- the reason there is a cap at all. 6-8 is the useful range in 2D:
# a corridor with two walls, a far end and an obstacle is 4-5 faces, and
# past ~8 the extra faces are shaving corners off free space the car cannot
# reach inside one horizon anyway.
MAX_FACES_DEFAULT = 8

# Two candidate faces whose normals are within this angle of each other are
# MERGED into one rather than both being kept -- see inflate_polytope's own
# "MERGE INTO A NEAR-PARALLEL EXISTING FACE" comment for why this is a
# correctness requirement and not an optimisation. 10 deg is well outside the
# sub-degree spread the parallel-wall fan produces, and well inside the
# angle between two genuinely different walls (90 deg in a corridor, 45 deg
# at the shallowest corner worth representing separately).
DEDUP_ANGLE_DEG_DEFAULT = 10.0

# Numerical floor for "the obstacle is on top of the seed" -- below this the
# seed->obstacle direction is undefined and the face is unusable.
_MIN_SEPARATION = 1e-9


def _leading_covered(
        seeds: np.ndarray, faces_n: List[np.ndarray], faces_b: List[float],
        limit: int) -> int:
    """Length of the longest LEADING run of seeds[:limit] satisfying every face.

    Helper for inflate_polytope's per-iteration coverage truncation -- see
    that function's own "WHAT HAPPENS ON A BEND" docstring section for why
    coverage is a prefix rather than an arbitrary subset.
    """
    if limit <= 0 or not faces_n:
        return max(limit, 0)
    A = np.stack(faces_n, axis=0)
    b = np.array(faces_b, dtype=float)
    residual = seeds[:limit] @ A.T - b[None, :]
    bad = np.nonzero(np.any(residual >= 0.0, axis=1))[0]
    return int(bad[0]) if bad.size else limit


def classify_local_cells(
        grid_data, width: int, height: int, resolution: float,
        origin_x: float, origin_y: float,
        seed_x: float, seed_y: float, r_local: float,
        occupied_threshold: float) -> Tuple[np.ndarray, Dict]:
    """Blocked cell CENTRES (map frame) within `r_local` of (seed_x, seed_y),
    plus a stats dict.

    Returns (points, stats) where `points` is an (M, 2) float array of map-
    frame cell centres that are blocked, and `stats` carries:

        n_cells          cells examined inside the disc
        n_blocked        how many of them were blocked
        n_occupied       blocked because value >= occupied_threshold
        n_unknown        blocked because value < 0 (OccupancyGrid's -1)
        n_out_of_bounds  blocked because the index lies outside the grid
        unknown_fraction n_unknown / n_cells (0.0 when n_cells == 0)
        oob_fraction     n_out_of_bounds / n_cells

    THE THREE CASES, each an explicit branch (see module docstring):
    occupied, unknown (-1), and outside the grid are ALL blocked. The
    in-bounds test is a real mask computed before any lookup -- the index
    window deliberately is NOT clipped to the grid first, because clipping is
    what silently converts "off the edge of the known world" into "not
    examined", and this function's whole contract is that it never does that.

    WHAT TODAY'S PERMISSIVE HANDLING ACTUALLY DOES, measured rather than
    asserted (2026-09-09, synthetic 20x20 grid, res 0.1, origin (0, 0), so
    the grid covers x,y in [0, 2]; one fully-occupied wall row; robot facing
    +x; costmap_boundary.extract_boundary_constraints + front_clearance_
    from_extraction, max_range 5.0):

        robot at (1.0, 1.0)   inside the grid        front=None  clearance 6.00
        robot at (50.0, 50.0) far outside the grid   front=None  clearance 6.00
        robot at (2.5, 1.0)   just past the +x edge  front=None  clearance 6.00

    A robot outside its own map reports SIX METRES OF CLEAR ROAD AHEAD. The
    existing _crop_indices clamps the search window to the grid extent, the
    clamped window comes out empty, "no occupied cell found" is returned, and
    front_clearance_from_extraction turns that into max_range_m + 1.0 -- the
    honest answer for "nothing seen in an observed area", the exactly-wrong
    answer for "the area was never in the map to begin with".

    Bearing on the standing URGENT bug (car stationary, costmap position
    drifting, missions stopping instantly): the open hypothesis was that an
    out-of-bounds lookup returns a FALSE OCCUPIED. The measurement above
    disproves that for this code path -- out-of-bounds fails PERMISSIVE, not
    restrictive, so it can only ever make a mission fail to stop, never stop
    instantly. It is a real bug, and the opposite one. See this module's
    commit message and costmap_boundary_node.py's own docstring for where
    that leaves the instant-stop symptom.
    """
    seed = np.array([seed_x, seed_y], dtype=float)

    # Index window covering the disc, in RAW index space -- deliberately not
    # clipped to [0, width) / [0, height). Out-of-range indices are kept and
    # classified as out-of-bounds below; clipping here is precisely the bug
    # documented in this function's own docstring.
    col_lo = int(math.floor((seed_x - r_local - origin_x) / resolution))
    col_hi = int(math.ceil((seed_x + r_local - origin_x) / resolution)) + 1
    row_lo = int(math.floor((seed_y - r_local - origin_y) / resolution))
    row_hi = int(math.ceil((seed_y + r_local - origin_y) / resolution)) + 1

    cols = np.arange(col_lo, col_hi)
    rows = np.arange(row_lo, row_hi)
    if cols.size == 0 or rows.size == 0:
        return np.zeros((0, 2), dtype=float), _empty_stats()

    # Cell centres (+0.5), the same convention costmap_boundary.py's own
    # nearest_occupied_in_window and costmap_renderer.py's world_to_pixel
    # already use -- not the cell's (col, row) corner.
    cell_x = origin_x + (cols.astype(np.float64) + 0.5) * resolution
    cell_y = origin_y + (rows.astype(np.float64) + 0.5) * resolution
    grid_x, grid_y = np.meshgrid(cell_x, cell_y)

    inside_disc = np.hypot(grid_x - seed_x, grid_y - seed_y) <= r_local
    if not np.any(inside_disc):
        return np.zeros((0, 2), dtype=float), _empty_stats()

    col_mesh, row_mesh = np.meshgrid(cols, rows)
    in_bounds = (
        (col_mesh >= 0) & (col_mesh < width) &
        (row_mesh >= 0) & (row_mesh < height)
    )

    # np.int16, not int8: slam_toolbox's -1/0-100 convention survives the
    # cast intact, the same reason costmap_renderer.py's own occupancy_to_rgb
    # already uses int16 here.
    arr = np.asarray(grid_data, dtype=np.int16).reshape(height, width)
    # Gather with the out-of-range indices neutralised so the fancy-index
    # itself is always valid; every position where in_bounds is False has its
    # value discarded immediately below, so the clipped lookup never leaks
    # into a classification.
    safe_cols = np.clip(col_mesh, 0, width - 1)
    safe_rows = np.clip(row_mesh, 0, height - 1)
    values = arr[safe_rows, safe_cols]

    # ---- the three named cases, each its own mask, none of them a default.
    out_of_bounds = (~in_bounds) & inside_disc
    occupied = in_bounds & inside_disc & (values >= occupied_threshold)
    unknown = in_bounds & inside_disc & (values < 0)
    blocked = out_of_bounds | occupied | unknown

    n_cells = int(np.count_nonzero(inside_disc))
    stats = {
        'n_cells': n_cells,
        'n_blocked': int(np.count_nonzero(blocked)),
        'n_occupied': int(np.count_nonzero(occupied)),
        'n_unknown': int(np.count_nonzero(unknown)),
        'n_out_of_bounds': int(np.count_nonzero(out_of_bounds)),
        'unknown_fraction': (
            float(np.count_nonzero(unknown)) / n_cells if n_cells else 0.0),
        'oob_fraction': (
            float(np.count_nonzero(out_of_bounds)) / n_cells if n_cells else 0.0),
    }

    points = np.stack([grid_x[blocked], grid_y[blocked]], axis=1)
    del seed  # only used for the disc test above; kept explicit for clarity.
    return points.astype(float), stats


def _empty_stats() -> Dict:
    """Stats for a window that contained no cells at all -- every count zero
    rather than a missing key, so a caller can log the dict unconditionally."""
    return {
        'n_cells': 0, 'n_blocked': 0, 'n_occupied': 0, 'n_unknown': 0,
        'n_out_of_bounds': 0, 'unknown_fraction': 0.0, 'oob_fraction': 0.0,
    }


def inflate_polytope(
        seed_points: Sequence[Sequence[float]],
        blocked_points: Sequence[Sequence[float]],
        max_faces: int = MAX_FACES_DEFAULT,
        dedup_angle_deg: float = DEDUP_ANGLE_DEG_DEFAULT) -> Dict:
    """IRIS-style iterative convex decomposition around a REFERENCE ARC.

    `seed_points`: (K, 2) samples along the corridor centreline, IN ORDER
    from the start of the arc outward -- the ordering is load-bearing, see
    `covered_fraction` below. `blocked_points`: (M, 2) from
    classify_local_cells. Both map frame.

    Returns a dict:
        A                (F, 2) unit face normals, pointing AWAY from the
                         free side and TOWARD the obstacle that generated
                         the face -- BoundaryConstraint.msg's own sign
                         convention exactly, so {x : A x <= b} is the free
                         set.
        b                (F,) face offsets, b_i = n_i . p_i with p_i the
                         obstacle cell the face is tangent at.
        n_faces          F
        cap_hit          True if the loop stopped because it reached
                         max_faces while blocked points were still
                         un-separated -- i.e. the polytope is NOT a complete
                         separation and some blocked cells remain inside it.
        n_unseparated    how many blocked points are still inside when the
                         loop ends (0 unless cap_hit).
        covered_points   (C, 2) the leading run of seed_points the polytope
                         actually contains.
        covered_fraction C / K.

    THE LOOP, and why every face has an obstacle touching it: at each
    iteration the closest remaining blocked point p to the seed SET is
    chosen, along with the seed point s nearest to it. The face is the
    hyperplane through p with normal (p - s)/|p - s| -- tangent at p, so p
    lies exactly ON the face and nothing is cut off anywhere a real
    observation is not touching. Every blocked point on the far side is then
    discarded (it is already excluded by this face) and the loop repeats on
    what is left.

    WHY THE SEED IS SAFE. n . s = n . p - n . (p - s) = b - |p - s| < b, so
    the seed point that generated the face strictly satisfies it. That is
    the whole containment argument, and it covers only the ONE seed point
    involved -- a different, farther part of the arc can still fall outside
    the same face on a bend.

    WHAT HAPPENS ON A BEND. A single convex body cannot both contain a
    curved arc and exclude the obstacles on the inside of the curve. Rather
    than quietly returning a polytope the reference violates, this truncates
    the arc: after each face is added, `covered` is cut back to the longest
    LEADING run of seed points still satisfying every face so far. The
    invariant "every covered point satisfies A x <= b" therefore holds
    unconditionally at every iteration and on return, and the cost of a
    bend shows up as covered_fraction < 1.0 -- a number the caller can act
    on. The leading run specifically (not the whole satisfying subset)
    because the horizon is traversed in order: a covered prefix is a
    contiguous stretch of corridor the car actually drives, whereas a
    covered set with a hole in it would describe nothing useful.

    Faces are never dropped to protect coverage. An obstacle-separating face
    is a safety statement and the arc is a preference; when they conflict
    the arc gives way.
    """
    seeds = np.asarray(seed_points, dtype=float).reshape(-1, 2)
    points = np.asarray(blocked_points, dtype=float).reshape(-1, 2)
    if seeds.shape[0] == 0:
        raise ValueError('inflate_polytope needs at least one seed point')

    faces_n: List[np.ndarray] = []
    faces_b: List[float] = []
    remaining = points
    n_covered = seeds.shape[0]
    cap_hit = False
    n_merged = 0
    cos_dedup = math.cos(math.radians(dedup_angle_deg))

    while remaining.shape[0] > 0:
        if len(faces_n) >= max_faces:
            cap_hit = True
            break

        # Closest remaining blocked point to the seed SET (not to a single
        # seed): distances from every remaining point to every seed, then the
        # global minimum. Sizes here are small -- max a few thousand blocked
        # cells against ~100 seeds -- so the dense pairwise form is fine and
        # is clearer than a KD-tree for what it does.
        diff = remaining[:, None, :] - seeds[None, :, :]
        d2 = np.einsum('ijk,ijk->ij', diff, diff)
        flat = int(np.argmin(d2))
        i_pt, i_seed = np.unravel_index(flat, d2.shape)

        p = remaining[i_pt]
        s = seeds[i_seed]
        sep = math.sqrt(float(d2[i_pt, i_seed]))
        if sep < _MIN_SEPARATION:
            # A blocked cell sitting exactly on the reference: the seed->
            # obstacle direction is undefined, so no face can be built from
            # it. Dropping the point rather than fabricating a direction --
            # the condition is reported through n_unseparated, and a caller
            # seeing an obstacle ON its own centreline has a corridor
            # problem, not a constraint-geometry problem.
            keep = np.ones(remaining.shape[0], dtype=bool)
            keep[i_pt] = False
            remaining = remaining[keep]
            continue

        n_vec = (p - s) / sep
        b_val = float(n_vec @ p)

        # ---- MERGE INTO A NEAR-PARALLEL EXISTING FACE, if there is one.
        # Without this the algorithm is not merely inefficient, it is wrong
        # in the case it will meet most often. Measured on a 3 m straight
        # corridor between two walls 2 m apart (test_safe_corridor.py pins
        # it): the un-merged loop spends 6 of its 8 faces on ONE wall,
        # emitting a fan of nearly-identical planes, and never places a
        # single face on the other wall at all -- a polytope that does not
        # exclude a wall the car can drive into.
        #
        # The fan happens because the discard test is `n . q >= b`. For a
        # wall running parallel to the corridor, the face normal is tilted a
        # fraction of a degree off the wall's own normal (it is a seed->cell
        # direction, and the arc is shorter than the wall), so wall cells
        # further along survive by that fraction, generate the next face,
        # and so on -- each face separating a few centimetres of wall.
        #
        # Merging keeps the EXISTING normal and tightens its offset to touch
        # the new obstacle: b_j <- min(b_j, n_j . p). That only ever moves a
        # face inward, so it can never let a blocked point back in, and p is
        # guaranteed excluded afterwards (n_j . p >= b_j), which is what
        # keeps the loop terminating. The cost is a slightly conservative
        # cut, bounded by the dedup angle -- at 10 deg, under 1.5% of the
        # face's distance -- paid to keep faces aligned with walls instead
        # of fanned across one.
        merged = False
        if faces_n:
            alignment = np.array([float(fn @ n_vec) for fn in faces_n])
            j = int(np.argmax(alignment))
            if alignment[j] >= cos_dedup:
                faces_b[j] = min(faces_b[j], float(faces_n[j] @ p))
                remaining = remaining[(remaining @ faces_n[j]) < faces_b[j]]
                n_merged += 1
                merged = True

        if not merged:
            faces_n.append(n_vec)
            faces_b.append(b_val)
            # Drop every blocked point this face already excludes
            # (n . q >= b). Strict < keeps only points genuinely still
            # inside; p itself has n . p == b and so is always removed,
            # which is what guarantees the loop terminates.
            remaining = remaining[(remaining @ n_vec) < b_val]

        # Re-truncate the covered arc against EVERY face, not just the one
        # added: a merge tightens a face placed on an earlier iteration, so
        # coverage established against its old offset can no longer be
        # trusted. Recomputed from scratch (K x F, both small) rather than
        # incrementally, so the invariant does not depend on which branch
        # above ran.
        n_covered = _leading_covered(seeds, faces_n, faces_b, n_covered)

    if faces_n:
        A = np.stack(faces_n, axis=0)
        b = np.array(faces_b, dtype=float)
    else:
        A = np.zeros((0, 2), dtype=float)
        b = np.zeros((0,), dtype=float)

    covered = seeds[:n_covered]
    result = {
        'A': A,
        'b': b,
        'n_faces': int(A.shape[0]),
        'cap_hit': cap_hit,
        'n_unseparated': int(remaining.shape[0]),
        'covered_points': covered,
        'covered_fraction': float(n_covered) / float(seeds.shape[0]),
        'n_merged': n_merged,
    }

    # The invariant this whole design exists to provide. A violation means
    # the truncation logic above is broken, not that the map is awkward --
    # loud, not degraded, per this change's own verification requirement.
    assert_reference_contained(A, b, covered)
    return result


def assert_reference_contained(
        A: np.ndarray, b: np.ndarray, points: Sequence[Sequence[float]],
        tol: float = 1e-9) -> None:
    """Raise AssertionError unless every point in `points` satisfies
    A x <= b + tol.

    THE ONE ASSERTION THAT CARRIES THIS CHANGE. Seeding on the reference is
    only worth doing if the reference is genuinely inside the result; if it
    ever is not, the seeding is broken and the correct response is to fail
    loudly rather than hand the solver a reference it cannot track. Called
    unconditionally at the end of inflate_polytope, and again by the node on
    the constraints it is about to publish.

    `tol` absorbs floating-point round-off only (the face through the
    generating obstacle is exact to ~1e-16 here); it is not a slack budget.
    """
    pts = np.asarray(points, dtype=float).reshape(-1, 2)
    if pts.shape[0] == 0 or A.shape[0] == 0:
        return
    residual = pts @ A.T - b[None, :]
    worst = float(np.max(residual))
    if worst > tol:
        i_pt, i_face = np.unravel_index(int(np.argmax(residual)), residual.shape)
        raise AssertionError(
            'reference centreline violates its own polytope: point '
            f'({pts[i_pt][0]:+.4f}, {pts[i_pt][1]:+.4f}) breaches face {i_face} '
            f'(n=({A[i_face][0]:+.4f}, {A[i_face][1]:+.4f}), b={b[i_face]:+.4f}) '
            f'by {worst:.3e} m -- seeding is broken.')


def seed_clearance(A: np.ndarray, b: np.ndarray, seed_x: float, seed_y: float) -> float:
    """Radius of the largest ball centred on (seed_x, seed_y) that fits
    inside {x : A x <= b} -- min_i (b_i - n_i . seed), exact because every
    face normal is a unit vector.

    Not the polytope's Chebyshev radius (that is an LP over the whole body);
    this is the inscribed radius AT THE SEED, which is the quantity that
    actually matters here -- it says how much room the car has around the
    reference point it is being asked to track. Returns +inf for a polytope
    with no faces (nothing was blocked within r_local).
    """
    if A.shape[0] == 0:
        return math.inf
    seed = np.array([seed_x, seed_y], dtype=float)
    return float(np.min(b - A @ seed))


def polytope_vertices(
        A: np.ndarray, b: np.ndarray,
        centre: Sequence[float], bound: float) -> np.ndarray:
    """Vertices of {x : A x <= b}, clipped to a `bound`-half-width axis-
    aligned box around `centre`, in counter-clockwise order.

    Sutherland-Hodgman: start from the box's four corners and clip the
    polygon by each half-plane in turn. The box keeps the result finite for
    an open polytope (fewer than three faces, or faces that do not enclose),
    which is the normal case near an unexplored frontier -- without it the
    area below would be infinite and unreportable. Returns an (V, 2) array,
    empty if the constraints are mutually infeasible within the box.
    """
    cx, cy = float(centre[0]), float(centre[1])
    poly = [
        np.array([cx - bound, cy - bound]), np.array([cx + bound, cy - bound]),
        np.array([cx + bound, cy + bound]), np.array([cx - bound, cy + bound]),
    ]
    for i in range(A.shape[0]):
        n_vec = A[i]
        b_val = float(b[i])
        if not poly:
            break
        clipped: List[np.ndarray] = []
        for j in range(len(poly)):
            cur = poly[j]
            nxt = poly[(j + 1) % len(poly)]
            cur_in = float(n_vec @ cur) <= b_val
            nxt_in = float(n_vec @ nxt) <= b_val
            if cur_in:
                clipped.append(cur)
            if cur_in != nxt_in:
                denom = float(n_vec @ (nxt - cur))
                if abs(denom) > 1e-15:
                    t = (b_val - float(n_vec @ cur)) / denom
                    clipped.append(cur + t * (nxt - cur))
        poly = clipped
    if not poly:
        return np.zeros((0, 2), dtype=float)
    return np.stack(poly, axis=0)


def polygon_area(vertices: np.ndarray) -> float:
    """Shoelace area of a simple polygon, sign-independent. 0.0 for fewer
    than three vertices."""
    v = np.asarray(vertices, dtype=float).reshape(-1, 2)
    if v.shape[0] < 3:
        return 0.0
    x, y = v[:, 0], v[:, 1]
    return float(abs(np.dot(x, np.roll(y, -1)) - np.dot(y, np.roll(x, -1))) * 0.5)


def polytope_report(
        polytope: Dict, cell_stats: Dict, seed_x: float, seed_y: float,
        r_local: float, min_seed_clearance: float, min_area: float,
        min_covered_fraction: float) -> Dict:
    """Combine an inflate_polytope result and a classify_local_cells stats
    dict into one reportable summary, and DECIDE whether the polytope is
    degenerate.

    Adds to the merged dict:
        seed_clearance    inscribed radius at the seed (see seed_clearance)
        area              polygon area, clipped to the r_local box
        degenerate        True if the polytope is too small or covers too
                          little of the reference to be worth applying
        degenerate_reasons list of short strings naming each failing test

    DEGENERACY IS REPORTED, NEVER SILENTLY ABSORBED. Unknown cells are
    blocked (see module docstring), so a sparsely-explored area legitimately
    produces a small polytope -- that is the honest result, and the wrong
    response is to relax the unknown-cell handling until the polytope looks
    reasonable. The right response is to publish the flag and let the
    consumer refuse to apply the constraints, which is what
    costmap_boundary_node does with it.

    The three tests are independent and all are reported, so a caller can
    see whether a polytope failed because it is physically tiny
    (seed_clearance/area) or because the corridor bends out of it
    (covered_fraction) -- different problems with different fixes.
    """
    A, b = polytope['A'], polytope['b']
    clearance = seed_clearance(A, b, seed_x, seed_y)
    verts = polytope_vertices(A, b, (seed_x, seed_y), r_local)
    area = polygon_area(verts)

    reasons: List[str] = []
    if clearance < min_seed_clearance:
        reasons.append(f'seed_clearance {clearance:.3f} < {min_seed_clearance:.3f}')
    if area < min_area:
        reasons.append(f'area {area:.3f} < {min_area:.3f}')
    if polytope['covered_fraction'] < min_covered_fraction:
        reasons.append(
            f'covered_fraction {polytope["covered_fraction"]:.3f} '
            f'< {min_covered_fraction:.3f}')

    report = dict(cell_stats)
    report.update({
        'n_faces': polytope['n_faces'],
        'cap_hit': polytope['cap_hit'],
        'n_unseparated': polytope['n_unseparated'],
        'covered_fraction': polytope['covered_fraction'],
        'seed_clearance': clearance,
        'area': area,
        'degenerate': bool(reasons),
        'degenerate_reasons': reasons,
    })
    return report


def faces_to_car_frame(
        A: np.ndarray, b: np.ndarray,
        robot_x: float, robot_y: float, robot_yaw: float) -> List[Tuple[float, float, float]]:
    """Rewrite map-frame faces {n . x <= b} as car/base_link-frame
    (normal_x, normal_y, offset) tuples, matching what
    costmap_boundary.extract_boundary_constraints already publishes and what
    MPC_corr.py's own costmap_boundaries_callback already expects.

    DERIVATION. A map-frame point x relates to its car-frame coordinates
    x_car by x = p_robot + R(yaw) x_car, so

        n . x <= b
        n . (p_robot + R x_car) <= b
        (R^T n) . x_car <= b - n . p_robot

    i.e. normal_car = R(yaw)^T n (the same R(-yaw) rotation
    costmap_boundary.nearest_occupied_in_window already applies to its own
    map-frame deltas) and offset_car = b - n . p_robot. R^T is a rotation,
    so unit normals stay unit and the offset stays a true perpendicular
    distance -- BoundaryConstraint.msg's convention is preserved exactly,
    including the un-shrunk-by-any-margin part: no car_radius or safety
    margin is subtracted here, that stays the consumer's job.

    Publishing in base_link rather than map is what lets this drop into the
    existing consumer unchanged: MPC_corr transforms base_link -> its own
    odom-frame world with its own odom pose, so map never has to agree with
    odom numerically -- the two transforms compose through the robot, and
    the map -> odom offset (1.88 m and 32 deg on the run that motivated the
    corridor anchor fix) cancels instead of being applied twice or not at
    all.
    """
    cos_yaw, sin_yaw = math.cos(robot_yaw), math.sin(robot_yaw)
    out: List[Tuple[float, float, float]] = []
    for i in range(A.shape[0]):
        nx, ny = float(A[i][0]), float(A[i][1])
        car_nx = cos_yaw * nx + sin_yaw * ny
        car_ny = -sin_yaw * nx + cos_yaw * ny
        offset = float(b[i]) - (nx * robot_x + ny * robot_y)
        out.append((car_nx, car_ny, offset))
    return out


def build_safe_corridor(
        grid_data, width: int, height: int, resolution: float,
        origin_x: float, origin_y: float,
        centreline: Sequence[Sequence[float]],
        r_local: float, occupied_threshold: float,
        max_faces: int = MAX_FACES_DEFAULT,
        min_seed_clearance: float = 0.15,
        min_area: float = 0.25,
        min_covered_fraction: float = 0.25) -> Optional[Dict]:
    """End-to-end: occupancy grid + reference centreline -> polytope +
    report. The one entry point costmap_boundary_node calls.

    `centreline`: (K, 2) map-frame samples IN ORDER along the arc, already
    trimmed to the stretch this polytope should cover (the node trims to
    r_local ahead of the car -- see its own _corridor_seed_points). The
    FIRST sample is the seed the local window is centred on and the point
    seed_clearance/area are measured at, so it should be the corridor point
    nearest the car, not the far end.

    Returns None if `centreline` is empty -- "nothing to seed on", which is
    a normal startup state (no corridor received yet), not an error.
    """
    pts = np.asarray(centreline, dtype=float).reshape(-1, 2)
    if pts.shape[0] == 0:
        return None

    seed_x, seed_y = float(pts[0][0]), float(pts[0][1])
    blocked, cell_stats = classify_local_cells(
        grid_data, width, height, resolution, origin_x, origin_y,
        seed_x, seed_y, r_local, occupied_threshold)
    polytope = inflate_polytope(pts, blocked, max_faces=max_faces)
    report = polytope_report(
        polytope, cell_stats, seed_x, seed_y, r_local,
        min_seed_clearance, min_area, min_covered_fraction)
    return {'polytope': polytope, 'report': report, 'seed': (seed_x, seed_y)}
