"""Object classes a go_to_object move may target. GENERATED -- do not edit.

Written by tools/gen_intent_target_enum.py from the configured detector
checkpoint (yolo26s-seg.pt), alongside the go_to.target enum in llm's
intent_v1.json. Regenerate with that script after changing yolo_model;
test_go_to_object_schema.py fails when this and the schema disagree.
"""

SOURCE_MODEL = 'yolo26s-seg.pt'

OBJECT_CLASSES = frozenset({
    'airplane',
    'apple',
    'backpack',
    'banana',
    'baseball bat',
    'baseball glove',
    'bear',
    'bed',
    'bench',
    'bicycle',
    'bird',
    'boat',
    'book',
    'bottle',
    'bowl',
    'broccoli',
    'bus',
    'cake',
    'car',
    'carrot',
    'cat',
    'cell phone',
    'chair',
    'clock',
    'couch',
    'cow',
    'cup',
    'dining table',
    'dog',
    'donut',
    'elephant',
    'fire hydrant',
    'fork',
    'frisbee',
    'giraffe',
    'hair drier',
    'handbag',
    'horse',
    'hot dog',
    'keyboard',
    'kite',
    'knife',
    'laptop',
    'microwave',
    'motorcycle',
    'mouse',
    'orange',
    'oven',
    'parking meter',
    'person',
    'pizza',
    'potted plant',
    'refrigerator',
    'remote',
    'sandwich',
    'scissors',
    'sheep',
    'sink',
    'skateboard',
    'skis',
    'snowboard',
    'spoon',
    'sports ball',
    'stop sign',
    'suitcase',
    'surfboard',
    'teddy bear',
    'tennis racket',
    'tie',
    'toaster',
    'toilet',
    'toothbrush',
    'traffic light',
    'train',
    'truck',
    'tv',
    'umbrella',
    'vase',
    'wine glass',
    'zebra',
})
